(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["MaterialProperties`"];
Unprotect["MaterialProperties`*"];
ClearAll["MaterialProperties`*"];
ClearAll["MaterialProperties`Private`*"];
MaterialProperties::usage="use the REST API to get materials data from materialsproject.org.  https://materialsproject.org/docs/api section 4.3.1 for list of available properties. This implementation has limited functionality (2020-09-02), so try out the website or direct API calls instead of this wrapper function via URLBuild, URLExecute, and Association Key Mapping (e.g. <|\"a\"->b|>[\"a\"]). Specify a personal key by using SetKey[] as in SetKey[\"abcd123\"]. Alternatively, you can manually add it to your copy of MaterialProperties.m. I recommend workflow/GetDataFromARESTfulAPI for some basic guidelines on accessing APIs.

Example usage:
	MaterialProperties[\"Fe3C\"] (*get material properties for \!\(\*SubscriptBox[\(Fe\), \(3\)]\)C*)
	MaterialProperties[\"Fe3C\", \"spacegroup\"] (*get the spacegroup properties of \!\(\*SubscriptBox[\(Fe\), \(3\)]\)C*)
	MaterialProperties[\"Fe3C\", \"spacegroup\", \"number\"] (*get the spacegroup number of \!\(\*SubscriptBox[\(Fe\), \(3\)]\)C*) 
	MaterialProperties[\"Fe3C\", \"\" ,\"\" , 0] (*get material properties for all database entries of \!\(\*SubscriptBox[\(Fe\), \(3\)]\)C*)
	MaterialProperties[\"Fe3C\", \"\" ,\"\" , 4] (*get material properties for the first 4 database entries of \!\(\*SubscriptBox[\(Fe\), \(3\)]\)C (or all entries, if # entries < 4);
	MaterialProperties[\"Fe3C\", \"spacegroup\", \"number\", 0] (*get a list of possible spacegroup numbers for \!\(\*SubscriptBox[\(Fe\), \(3\)]\)C*)

General URI format: Get https://www.materialsproject.org/rest/v2/materials/{material id, formula, or chemical system}/vasp/{property}?API_KEY=YOUR_API_KEY
";
SetKey::usage="SetKey[myKey]";
Begin["Private`"];
Options[MaterialProperties]={"myKey"->""};
MaterialProperties[formula_String,property_:"",subproperty_:"",requestedEntries_Integer:1,OptionsPattern[]]:=
Module[{urlRoot,myKey,requestURI,response,maxEntries,numEntries,propertyKey,subpropertyKey,out},
urlRoot="https://www.materialsproject.org/rest/v2/materials/";
myKey=OptionValue["myKey"];
requestURI=URLBuild[{urlRoot,formula,"vasp",property},{"API_KEY"->myKey}];
response=URLExecute[requestURI,"rawJSON"];
maxEntries=Length@response;
If[requestedEntries==0, numEntries=maxEntries;, numEntries=Min[{maxEntries,requestedEntries}];];
If[property=="",propertyKey=Sequence[];,propertyKey=property;];
If[subproperty=="",subpropertyKey=Sequence[];,subpropertyKey=subproperty;];
out=Lookup[response,"response"][[#]][propertyKey][subpropertyKey]&/@Range[numEntries];
If[Length@out==1 &&requestedEntries==1 ,out[[1]],out]
];
SetKey[myKey_]:=SetOptions[MaterialProperties,"myKey"->myKey];
End[]
Protect["MaterialProperties`*"];
EndPackage[]



